version: "3.8"
services:
  db:
    image: docker.io/library/postgres:alpine
    environment:
      - POSTGRES_PASSWORD=wisdom
      - POSTGRES_DB=wisdom
      - POSTGRES_USER=wisdom
    networks:
      - dbnet
# Disabled because this doesn't work properly on MacOS.
# [33] CONTEXT:  writing block 0 of relation base/16384/2658
# 2023-01-17 21:46:56.579 UTC [33] LOG:  out of file descriptors: No file descriptors available; release and retry
#    volumes:
#      - $PWD/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
networks:
  dbnet:
