version: "3.8"
services:
  db:
    platform: linux/amd64
    image: docker.io/library/postgres:alpine
    environment:
      - POSTGRES_PASSWORD=wisdom
      - POSTGRES_DB=wisdom
      - POSTGRES_USER=wisdom
    networks:
      - dbnet
# Disabled because this doesn't work properly on MacOS.
# [33] CONTEXT:  writing block 0 of relation base/16384/2658
# 2023-01-17 21:46:56.579 UTC [33] LOG:  out of file descriptors: No file descriptors available; release and retry
#    volumes:
#      - $PWD/db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  prometheus:
    platform: linux/amd64
    image: docker.io/prom/prometheus
    command:
      - --config.file=/opt/prometheus/prometheus.yaml
      - --web.enable-lifecycle
    volumes:
      - $PWD/prometheus/:/opt/prometheus/
    ports:
      - "9090:9090"
    networks:
      - dbnet
  grafana:
    platform: linux/amd64
    image: docker.io/grafana/grafana:7.5.17
    environment:
      - GF_LOG_LEVEL=warn
    ports:
      - "13000:3000"
    volumes:
      - $PWD/grafana:/var/lib/grafana
    networks:
      - dbnet

networks:
  dbnet:
